POST HTTP://localhost:4000/api/emails HTTP/1.1
Content-Type: application/json

{
    "email": "admin@email.com"
}

###
GET HTTP://localhost:4000/api/emails HTTP/1.1

###

GET HTTP://localhost:4000/api/blogs/38bc2e40-bc1b-4c17-a51c-ac8e581cd63f HTTP/1.1

###

DELETE HTTP://localhost:4000/api/blogs/deaf2912-db55-44c8-a808-90196e7b95ce HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRlYWYyOTEyLWRiNTUtNDRjOC1hODA4LTkwMTk2ZTdiOTVjZSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcyNzkyMzY0NywiZXhwIjoxNzI3OTI3MjQ3fQ.X9fl_kUCQU77WLO9pO6k-alsfVjvdH316Vd9be36duY
